/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.agendamentoatendimento.view;

/**
 *
 * @author Paulo-Lehman
 */
public class OrcamentoRead extends javax.swing.JFrame {

    /**
     * Creates new form OrcamentoRead
     */
    public OrcamentoRead() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuNovo = new javax.swing.JMenu();
        itemMenuNovoTecnico = new javax.swing.JMenuItem();
        ìtemMenuNovoCliente = new javax.swing.JMenuItem();
        itemMenuNovoOrdem = new javax.swing.JMenuItem();
        itemMenuNovoOrcamento = new javax.swing.JMenuItem();
        menuVer = new javax.swing.JMenu();
        itemMenuVerTecnico = new javax.swing.JMenuItem();
        itemMenuVerCliente = new javax.swing.JMenuItem();
        itemMenuVerOrdem = new javax.swing.JMenuItem();
        itemMenuVerOrcamento = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemMenuAjudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuNovo.setText("Novo");

        itemMenuNovoTecnico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuNovoTecnico.setText("Técnico");
        itemMenuNovoTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuNovoTecnicoActionPerformed(evt);
            }
        });
        menuNovo.add(itemMenuNovoTecnico);

        ìtemMenuNovoCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        ìtemMenuNovoCliente.setText("Cliente");
        ìtemMenuNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ìtemMenuNovoClienteActionPerformed(evt);
            }
        });
        menuNovo.add(ìtemMenuNovoCliente);

        itemMenuNovoOrdem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuNovoOrdem.setText("Ordem de Serviço");
        itemMenuNovoOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuNovoOrdemActionPerformed(evt);
            }
        });
        menuNovo.add(itemMenuNovoOrdem);

        itemMenuNovoOrcamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuNovoOrcamento.setText("Orçamento");
        itemMenuNovoOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuNovoOrcamentoActionPerformed(evt);
            }
        });
        menuNovo.add(itemMenuNovoOrcamento);

        jMenuBar1.add(menuNovo);

        menuVer.setText("Ver");

        itemMenuVerTecnico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemMenuVerTecnico.setText("Técnico");
        itemMenuVerTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVerTecnicoActionPerformed(evt);
            }
        });
        menuVer.add(itemMenuVerTecnico);

        itemMenuVerCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemMenuVerCliente.setText("Cliente");
        itemMenuVerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVerClienteActionPerformed(evt);
            }
        });
        menuVer.add(itemMenuVerCliente);

        itemMenuVerOrdem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemMenuVerOrdem.setText("Ordem de Serviço");
        itemMenuVerOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVerOrdemActionPerformed(evt);
            }
        });
        menuVer.add(itemMenuVerOrdem);

        itemMenuVerOrcamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemMenuVerOrcamento.setText("Orçamento");
        itemMenuVerOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVerOrcamentoActionPerformed(evt);
            }
        });
        menuVer.add(itemMenuVerOrcamento);

        jMenuBar1.add(menuVer);

        menuAjuda.setText("Ajuda");

        itemMenuAjudaSobre.setText("Sobre...");
        itemMenuAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAjudaSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemMenuAjudaSobre);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuNovoTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuNovoTecnicoActionPerformed
        TecnicoCreate tecnicoCreate = new TecnicoCreate();
        tecnicoCreate.setVisible(true);
        tecnicoCreate.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuNovoTecnicoActionPerformed

    private void ìtemMenuNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ìtemMenuNovoClienteActionPerformed
        //        ClienteCreate clienteCreate = new ClienteCreate();
        //        clienteCreate.setVisible(true);
        //        clienteCreate.setLocationRelativeTo(null);
        //        this.setVisible(false);
    }//GEN-LAST:event_ìtemMenuNovoClienteActionPerformed

    private void itemMenuNovoOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuNovoOrdemActionPerformed
        OrdemServicoCreate ordemServicoCreate = new OrdemServicoCreate();
        ordemServicoCreate.setVisible(true);
        ordemServicoCreate.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuNovoOrdemActionPerformed

    private void itemMenuNovoOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuNovoOrcamentoActionPerformed
        OrcamentoCreate orcamentoCreate = new OrcamentoCreate();
        orcamentoCreate.setVisible(true);
        orcamentoCreate.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuNovoOrcamentoActionPerformed

    private void itemMenuVerTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVerTecnicoActionPerformed
        TecnicoRead tecnicoRead = new TecnicoRead();
        tecnicoRead.setVisible(true);
        tecnicoRead.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuVerTecnicoActionPerformed

    private void itemMenuVerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVerClienteActionPerformed
        //        ClienteRead clienteRead = new ClienteRead();
        //        clienteRead.setVisible(true);
        //        clienteRead.setLocationRelativeTo(null);
        //        this.setVisible(false);
    }//GEN-LAST:event_itemMenuVerClienteActionPerformed

    private void itemMenuVerOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVerOrdemActionPerformed
        OrdemServicoRead ordemServicoRead = new OrdemServicoRead();
        ordemServicoRead.setVisible(true);
        ordemServicoRead.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuVerOrdemActionPerformed

    private void itemMenuVerOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVerOrcamentoActionPerformed
        OrcamentoRead orcamentoRead = new OrcamentoRead();
        orcamentoRead.setVisible(true);
        orcamentoRead.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuVerOrcamentoActionPerformed

    private void itemMenuAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAjudaSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuAjudaSobreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuAjudaSobre;
    private javax.swing.JMenuItem itemMenuNovoOrcamento;
    private javax.swing.JMenuItem itemMenuNovoOrdem;
    private javax.swing.JMenuItem itemMenuNovoTecnico;
    private javax.swing.JMenuItem itemMenuVerCliente;
    private javax.swing.JMenuItem itemMenuVerOrcamento;
    private javax.swing.JMenuItem itemMenuVerOrdem;
    private javax.swing.JMenuItem itemMenuVerTecnico;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuNovo;
    private javax.swing.JMenu menuVer;
    private javax.swing.JMenuItem ìtemMenuNovoCliente;
    // End of variables declaration//GEN-END:variables
}
